KNOX-2597 - Falling back to AliasBasedTokenStateService in case of DB configuration issues
apache/knox pull request #441
Opened 2021-04-29 09:12 UTC by smolnar82

## What changes were proposed in this pull request?

The following features are implemented by this change:
- if there is a misconfiguration in JDBCTokenState service, the AliasBasedTokenStateService is going to be used instead of failing the Knox Gateway to start
- a new REST API is added to get the status of the token management backend
- on the `tokengen` UI there is new information displayed about token management

## How was this patch tested?

Updated and executed JUnit test. I also run manual testing:

1. Token management is disabled in the `homepage` topology
<img width="590" alt="Screen Shot 2021-04-29 at 10 25 03 AM" src="https://user-images.githubusercontent.com/34065904/116528018-99688480-a8db-11eb-838a-ab61abf2f4c9.png">

2. Token management is set to DB, but I misconfigured it in `gateway-site.xml` -> falling back to `AliasBasedtokenStateService`
<img width="592" alt="Screen Shot 2021-04-29 at 10 21 13 AM" src="https://user-images.githubusercontent.com/34065904/116527966-8c4b9580-a8db-11eb-8eb6-cb7d9c43bc3a.png">

3. Token management is set to DB, but I misconfigured it in `gateway-site.xml` -> falling back to `AliasBasedtokenStateService`. I also set `knox.token.exp.tokengen.allowed.tss.backends` in the `homepage.xml` to `JDBCTokenStateService`
<img width="584" alt="Screen Shot 2021-04-29 at 10 28 15 AM" src="https://user-images.githubusercontent.com/34065904/116528118-b9984380-a8db-11eb-8957-47daf53e81c4.png">

4. Token management is set to DB and made sure it's properly configured
<img width="585" alt="Screen Shot 2021-04-29 at 10 27 16 AM" src="https://user-images.githubusercontent.com/34065904/116528132-be5cf780-a8db-11eb-9f94-0178e6063e8c.png">

2021-04-30 13:00 UTC, lmccay requested changes
Looks good, Sandor.
Just a couple nits.

2021-05-02 18:24 UTC, smolnar82 commented on gateway-applications/src/main/resources/applications/tokengen/app/js/tokengen.js
> +                            $('#tokenStateServiceStatusInfo').hide();
It's not really duplicated as we show/hide different HTML elements in different if-else cases (info, warning, or error). However, it should've been clear from the code so I'm going to make it clearer.

2021-05-02 18:26 UTC, smolnar82 commented on gateway-server/src/main/java/org/apache/knox/gateway/services/factory/TokenStateServiceFactory.java
> +          service.init(gatewayConfig, options);
In `org.apache.knox.gateway.services.GatewayServiceFactory` the `init(...)` method is called on the particular token state service implementation, therefore `JDBCTokenStateService.init(...)` is called at least twice. This is the reason I added state in that class to make sure initialization logic is invoked only once.

2021-05-02 18:28 UTC, smolnar82 commented on gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
> +      //as of now, we allow keystore and DB back-end for the tokengen application
Going to make it clear.

2021-05-02 18:28 UTC, smolnar82 commented on gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
> +      tokenStateServiceStatusMap.put("tokenManagementEnabled", "true");
+1

2021-05-02 18:37 UTC, smolnar82 commented on gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
> +      //as of now, we allow keystore and DB back-end for the tokengen application
Done

2021-05-02 18:38 UTC, smolnar82 commented on gateway-applications/src/main/resources/applications/tokengen/app/js/tokengen.js
> +                            $('#tokenStateServiceStatusInfo').hide();
Done

2021-05-02 18:38 UTC, smolnar82 commented on gateway-service-knoxtoken/src/main/java/org/apache/knox/gateway/service/knoxtoken/TokenResource.java
> +      tokenStateServiceStatusMap.put("tokenManagementEnabled", "true");
Done

2021-05-03 14:47 UTC, pzampino approved these changes
LGTM

2021-05-03 19:32 UTC, merged